name: fidelizacion_tecnicos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  retrofit: ^4.0.0
  provider: ^6.0.0
  json_annotation: ^4.9.0
  http: ^0.13.4 
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^18.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.0
  json_serializable: ^6.6.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: "^0.14.2"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo_png.png
    - assets/others/background_JD.gif
    - assets/others/fondo_cumpleaños.jpg
    - assets/others/fondo_default.jpg
